// <auto-generated />
using System;
using DATA.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DATA.Migrations
{
    [DbContext(typeof(RecipeContext))]
    [Migration("20210624113806_AddingUnitsTable")]
    partial class AddingUnitsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DATA.Models.IngredientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("308e5a53-f008-4edf-b283-ba70b6968576"),
                            Name = "chicken stock"
                        },
                        new
                        {
                            Id = new Guid("0bb72029-3d54-4f28-b896-a75ec55d81be"),
                            Name = "frozen peas"
                        },
                        new
                        {
                            Id = new Guid("9e454d8a-b0e1-4fcb-b5f6-575070f96c72"),
                            Name = "tarragon leaves"
                        },
                        new
                        {
                            Id = new Guid("433d77b6-4602-43cc-bc64-c62da06b8fff"),
                            Name = "salt"
                        },
                        new
                        {
                            Id = new Guid("4b69d56f-176b-48b0-94d7-1fbc65a8f70e"),
                            Name = "pancetta"
                        },
                        new
                        {
                            Id = new Guid("be126c12-5998-46e3-b450-9a85e2242c72"),
                            Name = "vegetable oil"
                        },
                        new
                        {
                            Id = new Guid("1ff10181-de94-476f-b657-fd8aa7686736"),
                            Name = "soy sauce"
                        },
                        new
                        {
                            Id = new Guid("84be7caf-9d2e-40ce-8f2f-4c01cfdcb223"),
                            Name = "honey"
                        },
                        new
                        {
                            Id = new Guid("95439689-3308-46f3-ad91-192023e77ddd"),
                            Name = "cucumber"
                        },
                        new
                        {
                            Id = new Guid("0f7b129b-5d0e-4982-bee0-540ba0fa92ae"),
                            Name = "pepper"
                        },
                        new
                        {
                            Id = new Guid("daa67c3a-b0c8-4707-bf39-693a29cfc3c3"),
                            Name = "salt"
                        },
                        new
                        {
                            Id = new Guid("8141cefb-a506-447a-b8dd-cba43f5f25f5"),
                            Name = "egg noodles"
                        },
                        new
                        {
                            Id = new Guid("9d909940-f887-408b-98c5-f2350a8b2e05"),
                            Name = "black pepper"
                        },
                        new
                        {
                            Id = new Guid("ae82332d-b27e-49f8-a690-2cc1aeb63cb6"),
                            Name = "peanuts"
                        },
                        new
                        {
                            Id = new Guid("2644293d-2a3b-4819-b0eb-05edbc6ec51d"),
                            Name = "chilli flakes"
                        },
                        new
                        {
                            Id = new Guid("ad2f6077-f629-4773-8202-920d252de06a"),
                            Name = "egg white"
                        },
                        new
                        {
                            Id = new Guid("fb09c9e3-b11b-4c18-b083-6e4245d188fa"),
                            Name = "caster sugar"
                        },
                        new
                        {
                            Id = new Guid("97ab3c3b-9d01-4a69-b6ef-28fb9f115551"),
                            Name = "ground almonds"
                        },
                        new
                        {
                            Id = new Guid("c911ef1d-cb84-47c3-a079-885dec537206"),
                            Name = "amaretto liqueur"
                        },
                        new
                        {
                            Id = new Guid("1933c878-caff-405c-81f8-21eb12101103"),
                            Name = "butter"
                        },
                        new
                        {
                            Id = new Guid("ed90189b-1ffe-4e12-b680-cbb8d64f91b5"),
                            Name = "egg"
                        },
                        new
                        {
                            Id = new Guid("b65f82ec-1870-4050-9382-72a23945d818"),
                            Name = "caster sugar"
                        },
                        new
                        {
                            Id = new Guid("7de01fa6-b56e-4b03-ab7e-7e3389e6b71b"),
                            Name = "plain flour"
                        },
                        new
                        {
                            Id = new Guid("c9f566b9-d445-4a66-8f5c-ef74cc70e1fa"),
                            Name = "lemon"
                        },
                        new
                        {
                            Id = new Guid("94d034a5-e336-4822-bab6-2a77f7af2a60"),
                            Name = "baking powder"
                        },
                        new
                        {
                            Id = new Guid("c3876b3d-4edc-4152-a611-145518c9f257"),
                            Name = "butter"
                        });
                });

            modelBuilder.Entity("DATA.Models.RecipeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Steps")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8945132d-8b1a-4ebe-8692-b36d8962f094"),
                            Author = "Nigel Slater",
                            Image = "https://imgur.com/2g8nS0W.jpg",
                            Name = "Pea soup with pancetta",
                            Steps = "Heat the chicken stock in a saucepan until it is simmering. Add the peas and simmer for 2 minutes, or until just tender. Stir in the tarragon and salt.##Transfer the mixture to a food processor and blend for a few short blasts to a rough-textured soup. Return the soup to the saucepan and keep warm over a low heat.##Using a pair of tongs, heat each slice of pancetta over the gas flame of your hob for a few seconds until it crisps up. (Alternatively, preheat your grill to its highest setting, lay the slices of pancetta onto a baking tray and grill for 1-2 minutes, or until crisp).##To serve, ladle the soup into bowls. Break the crisp pancetta into pieces and sprinkle on top of the soup."
                        },
                        new
                        {
                            Id = new Guid("9fb5a066-7a73-44dc-b832-3eb495abb741"),
                            Author = "Paul Rankin",
                            Image = "https://i.imgur.com/qvrXDy6.jpg",
                            Name = "Noodle salad with chilli nuts",
                            Steps = "For the noodle salad, put the vegetable oil, soy sauce and honey in a large bowl and mix well.##Add the cucumber, pepper and cooked noodles, season with salt and pepper and mix well.##For the chilli nuts, heat the vegetable oil in a frying pan over a medium heat and fry the peanuts for 3-4 minutes. Drain off the oil and fry for a further 2-3 minutes, then add the salt and chilli and stir well to coat the nuts.##Put the noodle salad in a bowl, sprinkle over the nuts and serve."
                        },
                        new
                        {
                            Id = new Guid("73cdf4dd-2ca7-454d-9116-f177f3a4a19a"),
                            Author = "Gino D'Acampo",
                            Image = "https://i.imgur.com/HtxaFZ1.jpg",
                            Name = "Amaretti biscuits",
                            Steps = "Preheat the oven to 170C/325F/Gas 3.##In a large bowl beat the egg whites until firm. Mix the sugar and the almonds gently into it. Add the amaretto liquor and fold in gently until you have a smooth paste.##Place some baking paper on a baking tray and lightly brush with butter. Using a teaspoon place small heaps of the mixture approximately 2cm/¾in apart, as they will expand while cooking. Bake for approximately 15 minutes until golden brown. Leave to cool slightly then serve or store in an air-tight container."
                        },
                        new
                        {
                            Id = new Guid("97bd149a-a4ad-4d7b-a44a-cc305c2e864d"),
                            Author = "Michel Roux Jr.",
                            Image = "https://i.imgur.com/cJSPnE1.jpg",
                            Name = "Madeleines",
                            Steps = "Preheat the oven to 200C/400F/Gas 6. Brush the madeleine tray with melted butter then shake in a little flour to coat, tapping out the excess.##Whisk together the eggs and the sugar in a bowl until frothy. Lightly whisk in the remaining ingredients. Leave to stand for 20 minutes before carefully pouring into the prepared madeleine tray.##Bake for 8-10 minutes, or until the mixture has risen a little in the middle and is fully cooked through. Transfer the madeleines to a wire rack and leave for a few minutes to cool slightly. These are best eaten within an hour of cooking."
                        });
                });

            modelBuilder.Entity("DATA.Models.RecipeIngredientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IngredientEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Quantity")
                        .HasColumnType("float(8)");

                    b.Property<Guid>("RecipeEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UnitEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IngredientEntityId");

                    b.HasIndex("RecipeEntityId");

                    b.HasIndex("UnitEntityId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5bdcb397-1cf4-4088-8fbb-d463d9900cc8"),
                            IngredientEntityId = new Guid("308e5a53-f008-4edf-b283-ba70b6968576"),
                            Quantity = 1f,
                            RecipeEntityId = new Guid("8945132d-8b1a-4ebe-8692-b36d8962f094"),
                            UnitEntityId = new Guid("5a15de50-d85e-4616-b1c4-375b493e1ea1")
                        },
                        new
                        {
                            Id = new Guid("8fadce76-c002-4379-b5cf-9cd4cc5fb121"),
                            IngredientEntityId = new Guid("0bb72029-3d54-4f28-b896-a75ec55d81be"),
                            Quantity = 500f,
                            RecipeEntityId = new Guid("8945132d-8b1a-4ebe-8692-b36d8962f094"),
                            UnitEntityId = new Guid("9a82ae2e-b356-4110-9dc4-db99fa37e0a5")
                        },
                        new
                        {
                            Id = new Guid("d849d89a-cef7-4a01-a727-84b56d9fdc61"),
                            IngredientEntityId = new Guid("9e454d8a-b0e1-4fcb-b5f6-575070f96c72"),
                            Quantity = 10f,
                            RecipeEntityId = new Guid("8945132d-8b1a-4ebe-8692-b36d8962f094"),
                            UnitEntityId = new Guid("9a82ae2e-b356-4110-9dc4-db99fa37e0a5")
                        },
                        new
                        {
                            Id = new Guid("05a38e17-3347-4b0b-92b4-09884b14ac38"),
                            IngredientEntityId = new Guid("433d77b6-4602-43cc-bc64-c62da06b8fff"),
                            Quantity = 1f,
                            RecipeEntityId = new Guid("8945132d-8b1a-4ebe-8692-b36d8962f094"),
                            UnitEntityId = new Guid("76be1b7e-331c-4731-9321-89a2e3e64755")
                        },
                        new
                        {
                            Id = new Guid("aa41b8c8-762e-4271-8c1b-262f92c7f8fe"),
                            IngredientEntityId = new Guid("4b69d56f-176b-48b0-94d7-1fbc65a8f70e"),
                            Quantity = 4f,
                            RecipeEntityId = new Guid("8945132d-8b1a-4ebe-8692-b36d8962f094"),
                            UnitEntityId = new Guid("e84fc472-f536-4779-9b1a-a55324d5b804")
                        },
                        new
                        {
                            Id = new Guid("962c0cdd-c5bc-4af7-930a-40d876c7735b"),
                            IngredientEntityId = new Guid("be126c12-5998-46e3-b450-9a85e2242c72"),
                            Quantity = 1f,
                            RecipeEntityId = new Guid("9fb5a066-7a73-44dc-b832-3eb495abb741"),
                            UnitEntityId = new Guid("a2755473-89f1-4444-8809-eef178cb3a7d")
                        },
                        new
                        {
                            Id = new Guid("4cb837ac-badf-421a-8aed-d3414bc96a1f"),
                            IngredientEntityId = new Guid("1ff10181-de94-476f-b657-fd8aa7686736"),
                            Quantity = 1f,
                            RecipeEntityId = new Guid("9fb5a066-7a73-44dc-b832-3eb495abb741"),
                            UnitEntityId = new Guid("a2755473-89f1-4444-8809-eef178cb3a7d")
                        },
                        new
                        {
                            Id = new Guid("12165496-305c-4608-979d-f60d4c401270"),
                            IngredientEntityId = new Guid("84be7caf-9d2e-40ce-8f2f-4c01cfdcb223"),
                            Quantity = 2f,
                            RecipeEntityId = new Guid("9fb5a066-7a73-44dc-b832-3eb495abb741"),
                            UnitEntityId = new Guid("a2755473-89f1-4444-8809-eef178cb3a7d")
                        },
                        new
                        {
                            Id = new Guid("13bedfd2-8463-4277-a719-88b2cfb1dcbd"),
                            IngredientEntityId = new Guid("95439689-3308-46f3-ad91-192023e77ddd"),
                            Quantity = 0.25f,
                            RecipeEntityId = new Guid("9fb5a066-7a73-44dc-b832-3eb495abb741"),
                            UnitEntityId = new Guid("79bfa2ce-1959-4358-a871-e9207c7166cd")
                        },
                        new
                        {
                            Id = new Guid("346a2cb6-9d29-4d19-a23e-4c236c44bb12"),
                            IngredientEntityId = new Guid("0f7b129b-5d0e-4982-bee0-540ba0fa92ae"),
                            Quantity = 0.25f,
                            RecipeEntityId = new Guid("9fb5a066-7a73-44dc-b832-3eb495abb741"),
                            UnitEntityId = new Guid("79bfa2ce-1959-4358-a871-e9207c7166cd")
                        },
                        new
                        {
                            Id = new Guid("6c632941-a6ec-47f1-a4ed-731673b282c7"),
                            IngredientEntityId = new Guid("daa67c3a-b0c8-4707-bf39-693a29cfc3c3"),
                            Quantity = 0.5f,
                            RecipeEntityId = new Guid("9fb5a066-7a73-44dc-b832-3eb495abb741"),
                            UnitEntityId = new Guid("a2755473-89f1-4444-8809-eef178cb3a7d")
                        },
                        new
                        {
                            Id = new Guid("1e32fd26-34da-46dc-ad66-1b18921f8788"),
                            IngredientEntityId = new Guid("8141cefb-a506-447a-b8dd-cba43f5f25f5"),
                            Quantity = 100f,
                            RecipeEntityId = new Guid("9fb5a066-7a73-44dc-b832-3eb495abb741"),
                            UnitEntityId = new Guid("9a82ae2e-b356-4110-9dc4-db99fa37e0a5")
                        },
                        new
                        {
                            Id = new Guid("b5c530e1-75e6-4381-af3f-e04dc435da69"),
                            IngredientEntityId = new Guid("9d909940-f887-408b-98c5-f2350a8b2e05"),
                            Quantity = 1f,
                            RecipeEntityId = new Guid("9fb5a066-7a73-44dc-b832-3eb495abb741"),
                            UnitEntityId = new Guid("76be1b7e-331c-4731-9321-89a2e3e64755")
                        },
                        new
                        {
                            Id = new Guid("d6c4edd9-4afd-471c-af8c-4798548d14ab"),
                            IngredientEntityId = new Guid("be126c12-5998-46e3-b450-9a85e2242c72"),
                            Quantity = 1f,
                            RecipeEntityId = new Guid("9fb5a066-7a73-44dc-b832-3eb495abb741"),
                            UnitEntityId = new Guid("a2755473-89f1-4444-8809-eef178cb3a7d")
                        },
                        new
                        {
                            Id = new Guid("0b4adfe9-6e49-42ce-9d83-9e3600fcbaa3"),
                            IngredientEntityId = new Guid("ae82332d-b27e-49f8-a690-2cc1aeb63cb6"),
                            Quantity = 50f,
                            RecipeEntityId = new Guid("9fb5a066-7a73-44dc-b832-3eb495abb741"),
                            UnitEntityId = new Guid("9a82ae2e-b356-4110-9dc4-db99fa37e0a5")
                        },
                        new
                        {
                            Id = new Guid("4912f80f-2217-49ab-917e-ac91aa6dd18a"),
                            IngredientEntityId = new Guid("2644293d-2a3b-4819-b0eb-05edbc6ec51d"),
                            Quantity = 0.5f,
                            RecipeEntityId = new Guid("9fb5a066-7a73-44dc-b832-3eb495abb741"),
                            UnitEntityId = new Guid("a2755473-89f1-4444-8809-eef178cb3a7d")
                        },
                        new
                        {
                            Id = new Guid("8b2f5a48-efea-4c5c-81aa-267d045a4d7a"),
                            IngredientEntityId = new Guid("ad2f6077-f629-4773-8202-920d252de06a"),
                            Quantity = 4f,
                            RecipeEntityId = new Guid("73cdf4dd-2ca7-454d-9116-f177f3a4a19a"),
                            UnitEntityId = new Guid("79bfa2ce-1959-4358-a871-e9207c7166cd")
                        },
                        new
                        {
                            Id = new Guid("a4e84ce2-6314-4a50-8516-a1ec7a1280d0"),
                            IngredientEntityId = new Guid("fb09c9e3-b11b-4c18-b083-6e4245d188fa"),
                            Quantity = 340f,
                            RecipeEntityId = new Guid("73cdf4dd-2ca7-454d-9116-f177f3a4a19a"),
                            UnitEntityId = new Guid("9a82ae2e-b356-4110-9dc4-db99fa37e0a5")
                        },
                        new
                        {
                            Id = new Guid("7b0592a4-7ebe-4c4a-bf6c-01e17e6e4fbd"),
                            IngredientEntityId = new Guid("97ab3c3b-9d01-4a69-b6ef-28fb9f115551"),
                            Quantity = 340f,
                            RecipeEntityId = new Guid("73cdf4dd-2ca7-454d-9116-f177f3a4a19a"),
                            UnitEntityId = new Guid("9a82ae2e-b356-4110-9dc4-db99fa37e0a5")
                        },
                        new
                        {
                            Id = new Guid("688f28d8-d5f1-47fc-9185-5ad33c647e5d"),
                            IngredientEntityId = new Guid("c911ef1d-cb84-47c3-a079-885dec537206"),
                            Quantity = 30f,
                            RecipeEntityId = new Guid("73cdf4dd-2ca7-454d-9116-f177f3a4a19a"),
                            UnitEntityId = new Guid("4a867491-5cc3-4520-8631-b200ec11df5b")
                        },
                        new
                        {
                            Id = new Guid("5b3906c0-a73d-4187-b040-299c2393304e"),
                            IngredientEntityId = new Guid("1933c878-caff-405c-81f8-21eb12101103"),
                            Quantity = 1f,
                            RecipeEntityId = new Guid("73cdf4dd-2ca7-454d-9116-f177f3a4a19a"),
                            UnitEntityId = new Guid("e84fc472-f536-4779-9b1a-a55324d5b804")
                        },
                        new
                        {
                            Id = new Guid("05017401-aac1-4e6f-b8e6-8f57110f3b0a"),
                            IngredientEntityId = new Guid("ed90189b-1ffe-4e12-b680-cbb8d64f91b5"),
                            Quantity = 2f,
                            RecipeEntityId = new Guid("97bd149a-a4ad-4d7b-a44a-cc305c2e864d"),
                            UnitEntityId = new Guid("79bfa2ce-1959-4358-a871-e9207c7166cd")
                        },
                        new
                        {
                            Id = new Guid("367d0041-682e-4ffc-97f8-54972eb8bd2b"),
                            IngredientEntityId = new Guid("b65f82ec-1870-4050-9382-72a23945d818"),
                            Quantity = 100f,
                            RecipeEntityId = new Guid("97bd149a-a4ad-4d7b-a44a-cc305c2e864d"),
                            UnitEntityId = new Guid("9a82ae2e-b356-4110-9dc4-db99fa37e0a5")
                        },
                        new
                        {
                            Id = new Guid("131ee9f0-b9d4-4e0f-9e46-e80b17ffee63"),
                            IngredientEntityId = new Guid("7de01fa6-b56e-4b03-ab7e-7e3389e6b71b"),
                            Quantity = 100f,
                            RecipeEntityId = new Guid("97bd149a-a4ad-4d7b-a44a-cc305c2e864d"),
                            UnitEntityId = new Guid("9a82ae2e-b356-4110-9dc4-db99fa37e0a5")
                        },
                        new
                        {
                            Id = new Guid("118faa23-0da5-4fa7-aa1c-837534a4ac7c"),
                            IngredientEntityId = new Guid("c9f566b9-d445-4a66-8f5c-ef74cc70e1fa"),
                            Quantity = 1f,
                            RecipeEntityId = new Guid("97bd149a-a4ad-4d7b-a44a-cc305c2e864d"),
                            UnitEntityId = new Guid("79bfa2ce-1959-4358-a871-e9207c7166cd")
                        },
                        new
                        {
                            Id = new Guid("38635ec8-b850-4e28-889c-f3db0cbfd738"),
                            IngredientEntityId = new Guid("94d034a5-e336-4822-bab6-2a77f7af2a60"),
                            Quantity = 0.75f,
                            RecipeEntityId = new Guid("97bd149a-a4ad-4d7b-a44a-cc305c2e864d"),
                            UnitEntityId = new Guid("a2755473-89f1-4444-8809-eef178cb3a7d")
                        },
                        new
                        {
                            Id = new Guid("ff9b1804-cba2-4c94-94a9-5348e956c629"),
                            IngredientEntityId = new Guid("c3876b3d-4edc-4152-a611-145518c9f257"),
                            Quantity = 100f,
                            RecipeEntityId = new Guid("97bd149a-a4ad-4d7b-a44a-cc305c2e864d"),
                            UnitEntityId = new Guid("9a82ae2e-b356-4110-9dc4-db99fa37e0a5")
                        });
                });

            modelBuilder.Entity("DATA.Models.UnitEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5a15de50-d85e-4616-b1c4-375b493e1ea1"),
                            Name = "l"
                        },
                        new
                        {
                            Id = new Guid("9a82ae2e-b356-4110-9dc4-db99fa37e0a5"),
                            Name = "g"
                        },
                        new
                        {
                            Id = new Guid("76be1b7e-331c-4731-9321-89a2e3e64755"),
                            Name = "pinch"
                        },
                        new
                        {
                            Id = new Guid("e84fc472-f536-4779-9b1a-a55324d5b804"),
                            Name = "slice"
                        },
                        new
                        {
                            Id = new Guid("a2755473-89f1-4444-8809-eef178cb3a7d"),
                            Name = "tsp"
                        },
                        new
                        {
                            Id = new Guid("4a867491-5cc3-4520-8631-b200ec11df5b"),
                            Name = "ml"
                        },
                        new
                        {
                            Id = new Guid("79bfa2ce-1959-4358-a871-e9207c7166cd"),
                            Name = ""
                        });
                });

            modelBuilder.Entity("DATA.Models.RecipeIngredientEntity", b =>
                {
                    b.HasOne("DATA.Models.IngredientEntity", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATA.Models.RecipeEntity", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATA.Models.UnitEntity", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("DATA.Models.IngredientEntity", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("DATA.Models.RecipeEntity", b =>
                {
                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
