// <auto-generated />
using System;
using DATA.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DATA.Migrations
{
    [DbContext(typeof(RecipeContext))]
    [Migration("20210929134223_Photo")]
    partial class Photo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DATA.Models.IngredientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5f878328-2c36-4f1c-800c-d203abde81e6"),
                            Name = "chicken stock"
                        },
                        new
                        {
                            Id = new Guid("9422adeb-5ccb-4a50-bffd-dcec67fbff47"),
                            Name = "frozen peas"
                        },
                        new
                        {
                            Id = new Guid("2af7b379-86d8-41d1-99c7-70d3af9d171d"),
                            Name = "tarragon leaves"
                        },
                        new
                        {
                            Id = new Guid("245a838d-db03-4fd1-903d-de240e0c6190"),
                            Name = "salt"
                        },
                        new
                        {
                            Id = new Guid("ab16ad36-e632-4321-bb5a-4b2a2330e6cf"),
                            Name = "pancetta"
                        },
                        new
                        {
                            Id = new Guid("2a3295f4-3694-4025-9db2-98b32b804c5c"),
                            Name = "vegetable oil"
                        },
                        new
                        {
                            Id = new Guid("4a31878f-d468-459d-8f9c-1b5fa4f0b3c4"),
                            Name = "soy sauce"
                        },
                        new
                        {
                            Id = new Guid("9164d17c-a519-42e2-8738-4fb5cee5a5dd"),
                            Name = "honey"
                        },
                        new
                        {
                            Id = new Guid("dce1d95c-c45b-44aa-bdab-1d99bc785242"),
                            Name = "cucumber"
                        },
                        new
                        {
                            Id = new Guid("5b8f42cc-e315-4a61-88f9-32420c05515a"),
                            Name = "pepper"
                        },
                        new
                        {
                            Id = new Guid("68ff36f5-2219-4220-8a63-6a37b42823ae"),
                            Name = "salt"
                        },
                        new
                        {
                            Id = new Guid("1034ef76-39de-4b58-936c-7b02601db473"),
                            Name = "egg noodles"
                        },
                        new
                        {
                            Id = new Guid("f002d3e6-2f51-47fa-a41b-0013700a0c6b"),
                            Name = "black pepper"
                        },
                        new
                        {
                            Id = new Guid("398a68a9-1a70-4933-a1a5-0a0a5da4b8b6"),
                            Name = "peanuts"
                        },
                        new
                        {
                            Id = new Guid("3dd08c94-6842-4866-b874-b851080f0c69"),
                            Name = "chilli flakes"
                        },
                        new
                        {
                            Id = new Guid("47d2c8de-49ca-405c-b449-3bc9129c22f7"),
                            Name = "egg white"
                        },
                        new
                        {
                            Id = new Guid("9a27892b-67d8-4483-9032-5d98f1060e39"),
                            Name = "caster sugar"
                        },
                        new
                        {
                            Id = new Guid("3e0c8f6d-75e8-45bd-9ab7-4df10406b184"),
                            Name = "ground almonds"
                        },
                        new
                        {
                            Id = new Guid("31581a3b-ccb5-409c-9a93-8f99cd2a40db"),
                            Name = "amaretto liqueur"
                        },
                        new
                        {
                            Id = new Guid("7d1551f4-a175-4a78-be3b-1f392c6017d1"),
                            Name = "butter"
                        },
                        new
                        {
                            Id = new Guid("c1c8f1f8-1f8c-4ff8-93a1-515c49c392ae"),
                            Name = "egg"
                        },
                        new
                        {
                            Id = new Guid("52983c95-a7b8-4a04-a43d-a20c8add009c"),
                            Name = "caster sugar"
                        },
                        new
                        {
                            Id = new Guid("acfba0e1-4ddd-4537-9d38-e43044e62e4c"),
                            Name = "plain flour"
                        },
                        new
                        {
                            Id = new Guid("30952646-e14b-4cd0-8dc2-cb37dd58f0af"),
                            Name = "lemon"
                        },
                        new
                        {
                            Id = new Guid("a770db09-9cf5-461f-aa09-cabfef994d98"),
                            Name = "baking powder"
                        },
                        new
                        {
                            Id = new Guid("c3f7fc57-12e4-4cc5-9dee-ecb8171de302"),
                            Name = "butter"
                        });
                });

            modelBuilder.Entity("DATA.Models.RecipeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CreatedOn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Steps")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e0017473-a161-49a9-9e20-4365b283f834"),
                            Author = "Nigel Slater",
                            Image = "https://imgur.com/2g8nS0W.jpg",
                            Name = "Pea soup with pancetta",
                            Steps = "Heat the chicken stock in a saucepan until it is simmering. Add the peas and simmer for 2 minutes, or until just tender. Stir in the tarragon and salt.##Transfer the mixture to a food processor and blend for a few short blasts to a rough-textured soup. Return the soup to the saucepan and keep warm over a low heat.##Using a pair of tongs, heat each slice of pancetta over the gas flame of your hob for a few seconds until it crisps up. (Alternatively, preheat your grill to its highest setting, lay the slices of pancetta onto a baking tray and grill for 1-2 minutes, or until crisp).##To serve, ladle the soup into bowls. Break the crisp pancetta into pieces and sprinkle on top of the soup."
                        },
                        new
                        {
                            Id = new Guid("8c400dd5-c272-494f-9618-b52a605997b0"),
                            Author = "Paul Rankin",
                            Image = "https://i.imgur.com/qvrXDy6.jpg",
                            Name = "Noodle salad with chilli nuts",
                            Steps = "For the noodle salad, put the vegetable oil, soy sauce and honey in a large bowl and mix well.##Add the cucumber, pepper and cooked noodles, season with salt and pepper and mix well.##For the chilli nuts, heat the vegetable oil in a frying pan over a medium heat and fry the peanuts for 3-4 minutes. Drain off the oil and fry for a further 2-3 minutes, then add the salt and chilli and stir well to coat the nuts.##Put the noodle salad in a bowl, sprinkle over the nuts and serve."
                        },
                        new
                        {
                            Id = new Guid("d595819a-5497-4eb4-9d8a-2f31cb40f509"),
                            Author = "Gino D'Acampo",
                            Image = "https://i.imgur.com/HtxaFZ1.jpg",
                            Name = "Amaretti biscuits",
                            Steps = "Preheat the oven to 170C/325F/Gas 3.##In a large bowl beat the egg whites until firm. Mix the sugar and the almonds gently into it. Add the amaretto liquor and fold in gently until you have a smooth paste.##Place some baking paper on a baking tray and lightly brush with butter. Using a teaspoon place small heaps of the mixture approximately 2cm/¾in apart, as they will expand while cooking. Bake for approximately 15 minutes until golden brown. Leave to cool slightly then serve or store in an air-tight container."
                        },
                        new
                        {
                            Id = new Guid("75c4ab50-679b-4f7d-91c1-ad4638ddaad3"),
                            Author = "Michel Roux Jr.",
                            Image = "https://i.imgur.com/cJSPnE1.jpg",
                            Name = "Madeleines",
                            Steps = "Preheat the oven to 200C/400F/Gas 6. Brush the madeleine tray with melted butter then shake in a little flour to coat, tapping out the excess.##Whisk together the eggs and the sugar in a bowl until frothy. Lightly whisk in the remaining ingredients. Leave to stand for 20 minutes before carefully pouring into the prepared madeleine tray.##Bake for 8-10 minutes, or until the mixture has risen a little in the middle and is fully cooked through. Transfer the madeleines to a wire rack and leave for a few minutes to cool slightly. These are best eaten within an hour of cooking."
                        });
                });

            modelBuilder.Entity("DATA.Models.RecipeIngredientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IngredientEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Quantity")
                        .HasColumnType("float(8)");

                    b.Property<Guid>("RecipeEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UnitEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IngredientEntityId");

                    b.HasIndex("RecipeEntityId");

                    b.HasIndex("UnitEntityId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4ac2b896-7539-438f-b03e-03c0fcf426c3"),
                            IngredientEntityId = new Guid("5f878328-2c36-4f1c-800c-d203abde81e6"),
                            Quantity = 1f,
                            RecipeEntityId = new Guid("e0017473-a161-49a9-9e20-4365b283f834"),
                            UnitEntityId = new Guid("216369d9-e85e-4643-8013-232b2d7b12f1")
                        },
                        new
                        {
                            Id = new Guid("71fa09b0-666a-41fb-97f0-e2581b3552ba"),
                            IngredientEntityId = new Guid("9422adeb-5ccb-4a50-bffd-dcec67fbff47"),
                            Quantity = 500f,
                            RecipeEntityId = new Guid("e0017473-a161-49a9-9e20-4365b283f834"),
                            UnitEntityId = new Guid("ead55dd2-9def-497e-ae79-7744c136e2e7")
                        },
                        new
                        {
                            Id = new Guid("b746e474-4d29-4a02-bdbb-c77fd398048a"),
                            IngredientEntityId = new Guid("2af7b379-86d8-41d1-99c7-70d3af9d171d"),
                            Quantity = 10f,
                            RecipeEntityId = new Guid("e0017473-a161-49a9-9e20-4365b283f834"),
                            UnitEntityId = new Guid("ead55dd2-9def-497e-ae79-7744c136e2e7")
                        },
                        new
                        {
                            Id = new Guid("5b40c3df-fd39-414e-bc18-46d6f91535f6"),
                            IngredientEntityId = new Guid("245a838d-db03-4fd1-903d-de240e0c6190"),
                            Quantity = 1f,
                            RecipeEntityId = new Guid("e0017473-a161-49a9-9e20-4365b283f834"),
                            UnitEntityId = new Guid("c0e06254-1a34-46b1-afee-207afe20d0e8")
                        },
                        new
                        {
                            Id = new Guid("beee528e-9159-439f-a170-0cd0d4c0b2d0"),
                            IngredientEntityId = new Guid("ab16ad36-e632-4321-bb5a-4b2a2330e6cf"),
                            Quantity = 4f,
                            RecipeEntityId = new Guid("e0017473-a161-49a9-9e20-4365b283f834"),
                            UnitEntityId = new Guid("bbe66c8f-d082-47c4-85dc-0844c5a08db1")
                        },
                        new
                        {
                            Id = new Guid("1cfa9e59-779f-4319-a188-1475c2cbc6db"),
                            IngredientEntityId = new Guid("2a3295f4-3694-4025-9db2-98b32b804c5c"),
                            Quantity = 1f,
                            RecipeEntityId = new Guid("8c400dd5-c272-494f-9618-b52a605997b0"),
                            UnitEntityId = new Guid("021f2c65-263e-4cd5-a8a6-480e477ba2a0")
                        },
                        new
                        {
                            Id = new Guid("731fe628-7a0e-4300-ab86-4dad249eb48f"),
                            IngredientEntityId = new Guid("4a31878f-d468-459d-8f9c-1b5fa4f0b3c4"),
                            Quantity = 1f,
                            RecipeEntityId = new Guid("8c400dd5-c272-494f-9618-b52a605997b0"),
                            UnitEntityId = new Guid("021f2c65-263e-4cd5-a8a6-480e477ba2a0")
                        },
                        new
                        {
                            Id = new Guid("bf00579a-986d-4bd5-b4ca-22dd3fa3ac01"),
                            IngredientEntityId = new Guid("9164d17c-a519-42e2-8738-4fb5cee5a5dd"),
                            Quantity = 2f,
                            RecipeEntityId = new Guid("8c400dd5-c272-494f-9618-b52a605997b0"),
                            UnitEntityId = new Guid("021f2c65-263e-4cd5-a8a6-480e477ba2a0")
                        },
                        new
                        {
                            Id = new Guid("322fead6-22ee-475b-9167-0e23b801c6a9"),
                            IngredientEntityId = new Guid("dce1d95c-c45b-44aa-bdab-1d99bc785242"),
                            Quantity = 0.25f,
                            RecipeEntityId = new Guid("8c400dd5-c272-494f-9618-b52a605997b0"),
                            UnitEntityId = new Guid("91a8fc93-bb2a-4e13-831f-2ca251afca05")
                        },
                        new
                        {
                            Id = new Guid("4cd6b110-932e-4570-bf4d-5457aa7a28b1"),
                            IngredientEntityId = new Guid("5b8f42cc-e315-4a61-88f9-32420c05515a"),
                            Quantity = 0.25f,
                            RecipeEntityId = new Guid("8c400dd5-c272-494f-9618-b52a605997b0"),
                            UnitEntityId = new Guid("91a8fc93-bb2a-4e13-831f-2ca251afca05")
                        },
                        new
                        {
                            Id = new Guid("cab1642f-dfd7-4c45-9783-f16fd30de6db"),
                            IngredientEntityId = new Guid("68ff36f5-2219-4220-8a63-6a37b42823ae"),
                            Quantity = 0.5f,
                            RecipeEntityId = new Guid("8c400dd5-c272-494f-9618-b52a605997b0"),
                            UnitEntityId = new Guid("021f2c65-263e-4cd5-a8a6-480e477ba2a0")
                        },
                        new
                        {
                            Id = new Guid("7f3cc657-ee23-4df6-91de-deb159fcce8d"),
                            IngredientEntityId = new Guid("1034ef76-39de-4b58-936c-7b02601db473"),
                            Quantity = 100f,
                            RecipeEntityId = new Guid("8c400dd5-c272-494f-9618-b52a605997b0"),
                            UnitEntityId = new Guid("ead55dd2-9def-497e-ae79-7744c136e2e7")
                        },
                        new
                        {
                            Id = new Guid("a05b735d-7b31-4ca6-9c6b-1d5343055acf"),
                            IngredientEntityId = new Guid("f002d3e6-2f51-47fa-a41b-0013700a0c6b"),
                            Quantity = 1f,
                            RecipeEntityId = new Guid("8c400dd5-c272-494f-9618-b52a605997b0"),
                            UnitEntityId = new Guid("c0e06254-1a34-46b1-afee-207afe20d0e8")
                        },
                        new
                        {
                            Id = new Guid("021ac317-8eab-4ca5-9fa1-62e33577ae0d"),
                            IngredientEntityId = new Guid("2a3295f4-3694-4025-9db2-98b32b804c5c"),
                            Quantity = 1f,
                            RecipeEntityId = new Guid("8c400dd5-c272-494f-9618-b52a605997b0"),
                            UnitEntityId = new Guid("021f2c65-263e-4cd5-a8a6-480e477ba2a0")
                        },
                        new
                        {
                            Id = new Guid("0380edc5-b210-4e51-a3a7-6a97e434d912"),
                            IngredientEntityId = new Guid("398a68a9-1a70-4933-a1a5-0a0a5da4b8b6"),
                            Quantity = 50f,
                            RecipeEntityId = new Guid("8c400dd5-c272-494f-9618-b52a605997b0"),
                            UnitEntityId = new Guid("ead55dd2-9def-497e-ae79-7744c136e2e7")
                        },
                        new
                        {
                            Id = new Guid("851abaa1-2d5c-43ff-b9d6-511bd5f4897b"),
                            IngredientEntityId = new Guid("3dd08c94-6842-4866-b874-b851080f0c69"),
                            Quantity = 0.5f,
                            RecipeEntityId = new Guid("8c400dd5-c272-494f-9618-b52a605997b0"),
                            UnitEntityId = new Guid("021f2c65-263e-4cd5-a8a6-480e477ba2a0")
                        },
                        new
                        {
                            Id = new Guid("d1ce30e1-efb0-43ba-a116-9bb315d03334"),
                            IngredientEntityId = new Guid("47d2c8de-49ca-405c-b449-3bc9129c22f7"),
                            Quantity = 4f,
                            RecipeEntityId = new Guid("d595819a-5497-4eb4-9d8a-2f31cb40f509"),
                            UnitEntityId = new Guid("91a8fc93-bb2a-4e13-831f-2ca251afca05")
                        },
                        new
                        {
                            Id = new Guid("f3280855-28e6-4d59-8606-145d67ec3ee0"),
                            IngredientEntityId = new Guid("9a27892b-67d8-4483-9032-5d98f1060e39"),
                            Quantity = 340f,
                            RecipeEntityId = new Guid("d595819a-5497-4eb4-9d8a-2f31cb40f509"),
                            UnitEntityId = new Guid("ead55dd2-9def-497e-ae79-7744c136e2e7")
                        },
                        new
                        {
                            Id = new Guid("241ee674-a23a-407c-b064-b5ea7daa4a68"),
                            IngredientEntityId = new Guid("3e0c8f6d-75e8-45bd-9ab7-4df10406b184"),
                            Quantity = 340f,
                            RecipeEntityId = new Guid("d595819a-5497-4eb4-9d8a-2f31cb40f509"),
                            UnitEntityId = new Guid("ead55dd2-9def-497e-ae79-7744c136e2e7")
                        },
                        new
                        {
                            Id = new Guid("b56d794a-007c-4001-8f78-230b9ae7bafd"),
                            IngredientEntityId = new Guid("31581a3b-ccb5-409c-9a93-8f99cd2a40db"),
                            Quantity = 30f,
                            RecipeEntityId = new Guid("d595819a-5497-4eb4-9d8a-2f31cb40f509"),
                            UnitEntityId = new Guid("4873ca4d-40c7-4f7c-9e3d-9365046f832b")
                        },
                        new
                        {
                            Id = new Guid("a2c104ef-6585-475c-89cb-8be94d2634dc"),
                            IngredientEntityId = new Guid("7d1551f4-a175-4a78-be3b-1f392c6017d1"),
                            Quantity = 1f,
                            RecipeEntityId = new Guid("d595819a-5497-4eb4-9d8a-2f31cb40f509"),
                            UnitEntityId = new Guid("bbe66c8f-d082-47c4-85dc-0844c5a08db1")
                        },
                        new
                        {
                            Id = new Guid("5c552942-e4c7-453a-a2ca-432623251f34"),
                            IngredientEntityId = new Guid("c1c8f1f8-1f8c-4ff8-93a1-515c49c392ae"),
                            Quantity = 2f,
                            RecipeEntityId = new Guid("75c4ab50-679b-4f7d-91c1-ad4638ddaad3"),
                            UnitEntityId = new Guid("91a8fc93-bb2a-4e13-831f-2ca251afca05")
                        },
                        new
                        {
                            Id = new Guid("df3f24c7-477c-4b10-ab0a-b601e5453392"),
                            IngredientEntityId = new Guid("52983c95-a7b8-4a04-a43d-a20c8add009c"),
                            Quantity = 100f,
                            RecipeEntityId = new Guid("75c4ab50-679b-4f7d-91c1-ad4638ddaad3"),
                            UnitEntityId = new Guid("ead55dd2-9def-497e-ae79-7744c136e2e7")
                        },
                        new
                        {
                            Id = new Guid("6fdc07af-d724-4222-8e37-9b902839b563"),
                            IngredientEntityId = new Guid("acfba0e1-4ddd-4537-9d38-e43044e62e4c"),
                            Quantity = 100f,
                            RecipeEntityId = new Guid("75c4ab50-679b-4f7d-91c1-ad4638ddaad3"),
                            UnitEntityId = new Guid("ead55dd2-9def-497e-ae79-7744c136e2e7")
                        },
                        new
                        {
                            Id = new Guid("e020cda2-3195-4910-ab49-a78fcd90bad3"),
                            IngredientEntityId = new Guid("30952646-e14b-4cd0-8dc2-cb37dd58f0af"),
                            Quantity = 1f,
                            RecipeEntityId = new Guid("75c4ab50-679b-4f7d-91c1-ad4638ddaad3"),
                            UnitEntityId = new Guid("91a8fc93-bb2a-4e13-831f-2ca251afca05")
                        },
                        new
                        {
                            Id = new Guid("66e81d86-bea6-4ed4-8200-be665baa71de"),
                            IngredientEntityId = new Guid("a770db09-9cf5-461f-aa09-cabfef994d98"),
                            Quantity = 0.75f,
                            RecipeEntityId = new Guid("75c4ab50-679b-4f7d-91c1-ad4638ddaad3"),
                            UnitEntityId = new Guid("021f2c65-263e-4cd5-a8a6-480e477ba2a0")
                        },
                        new
                        {
                            Id = new Guid("f099beb8-a192-4904-bc61-515a106e43d7"),
                            IngredientEntityId = new Guid("c3f7fc57-12e4-4cc5-9dee-ecb8171de302"),
                            Quantity = 100f,
                            RecipeEntityId = new Guid("75c4ab50-679b-4f7d-91c1-ad4638ddaad3"),
                            UnitEntityId = new Guid("ead55dd2-9def-497e-ae79-7744c136e2e7")
                        });
                });

            modelBuilder.Entity("DATA.Models.UnitEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = new Guid("216369d9-e85e-4643-8013-232b2d7b12f1"),
                            Name = "l"
                        },
                        new
                        {
                            Id = new Guid("ead55dd2-9def-497e-ae79-7744c136e2e7"),
                            Name = "g"
                        },
                        new
                        {
                            Id = new Guid("c0e06254-1a34-46b1-afee-207afe20d0e8"),
                            Name = "pinch"
                        },
                        new
                        {
                            Id = new Guid("bbe66c8f-d082-47c4-85dc-0844c5a08db1"),
                            Name = "slice"
                        },
                        new
                        {
                            Id = new Guid("021f2c65-263e-4cd5-a8a6-480e477ba2a0"),
                            Name = "tsp"
                        },
                        new
                        {
                            Id = new Guid("4873ca4d-40c7-4f7c-9e3d-9365046f832b"),
                            Name = "ml"
                        },
                        new
                        {
                            Id = new Guid("91a8fc93-bb2a-4e13-831f-2ca251afca05"),
                            Name = ""
                        });
                });

            modelBuilder.Entity("DATA.Models.RecipeIngredientEntity", b =>
                {
                    b.HasOne("DATA.Models.IngredientEntity", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATA.Models.RecipeEntity", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATA.Models.UnitEntity", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("DATA.Models.IngredientEntity", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("DATA.Models.RecipeEntity", b =>
                {
                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
