// <auto-generated />
using System;
using DATA.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DATA.Migrations
{
    [DbContext(typeof(RecipeContext))]
    [Migration("20210614105039_SeedingTesting5")]
    partial class SeedingTesting5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DATA.Models.IngredientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a2e7fe9d-62ce-499d-bad7-374d5f5ea324"),
                            Name = "chicken stock"
                        },
                        new
                        {
                            Id = new Guid("39cf9a94-6d89-4749-8b95-e46cf1f7e3f2"),
                            Name = "frozen peas"
                        },
                        new
                        {
                            Id = new Guid("6ec75545-bc1f-4d22-9567-a0332acac633"),
                            Name = "tarragon leaves"
                        },
                        new
                        {
                            Id = new Guid("60c1ee57-6b8d-4c7b-b7c4-c243ac4eb589"),
                            Name = "salt"
                        },
                        new
                        {
                            Id = new Guid("a8053e3a-81f4-4e9f-a873-4fe43132dabf"),
                            Name = "pancetta"
                        },
                        new
                        {
                            Id = new Guid("9298906d-329f-491f-9c56-acd583a3ac58"),
                            Name = "vegetable oil"
                        },
                        new
                        {
                            Id = new Guid("899c7d60-d9b5-4bcd-ad7f-bec831ada320"),
                            Name = "soy sauce"
                        },
                        new
                        {
                            Id = new Guid("e8433ed7-3926-42ca-a6a0-35ad096417c0"),
                            Name = "honey"
                        },
                        new
                        {
                            Id = new Guid("ab38a6df-ae99-4be9-b13c-c135fdb6edc4"),
                            Name = "cucumber"
                        },
                        new
                        {
                            Id = new Guid("c6a33876-00f8-43f7-85f1-bf09cbdb444c"),
                            Name = "pepper"
                        },
                        new
                        {
                            Id = new Guid("a255606f-ecbb-42a4-a19a-261667750af0"),
                            Name = "salt"
                        },
                        new
                        {
                            Id = new Guid("a3cbe4b2-22e0-466f-84ab-9e182fd412ad"),
                            Name = "egg noodles"
                        },
                        new
                        {
                            Id = new Guid("b1d5598b-19c6-462d-9245-880e16581ce5"),
                            Name = "black pepper"
                        },
                        new
                        {
                            Id = new Guid("4b702393-2272-4e1c-8227-78dab874decf"),
                            Name = "peanuts"
                        },
                        new
                        {
                            Id = new Guid("c54d0495-4fea-4746-a3a0-b6d0655e26e9"),
                            Name = "chilli flakes"
                        },
                        new
                        {
                            Id = new Guid("49c14bf5-f6d5-4dec-88b3-eb1b41da15a1"),
                            Name = "egg white"
                        },
                        new
                        {
                            Id = new Guid("318eed32-374a-440e-960a-b3b8d366975b"),
                            Name = "caster sugar"
                        },
                        new
                        {
                            Id = new Guid("42cb1156-0538-469d-9ff5-f2ff86f02b59"),
                            Name = "ground almonds"
                        },
                        new
                        {
                            Id = new Guid("4afffe88-426f-4556-ba73-cbff3022d052"),
                            Name = "amaretto liqueur"
                        },
                        new
                        {
                            Id = new Guid("21622f46-38a6-48b8-ae4e-4db58f4ca206"),
                            Name = "butter"
                        },
                        new
                        {
                            Id = new Guid("ef8a6b6c-b4b9-4731-9e97-b6070478ec78"),
                            Name = "egg"
                        },
                        new
                        {
                            Id = new Guid("726e428a-5f9d-4cd9-87a2-b3c8e007fce8"),
                            Name = "caster sugar"
                        },
                        new
                        {
                            Id = new Guid("6fa9c5bf-57ca-4092-a38f-808d569ed079"),
                            Name = "plain flour"
                        },
                        new
                        {
                            Id = new Guid("7175a1df-a56f-4f1e-97b5-4bcb3590f46a"),
                            Name = "lemon"
                        },
                        new
                        {
                            Id = new Guid("73d32e88-4808-4d46-aa39-5356e5abd1e4"),
                            Name = "baking powder"
                        },
                        new
                        {
                            Id = new Guid("4eba77e8-1217-4917-99b6-ce5825b04cc3"),
                            Name = "butter"
                        });
                });

            modelBuilder.Entity("DATA.Models.RecipeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Steps")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e953117d-9c83-4484-a67c-ab23d2e9d7a4"),
                            Author = "Nigel Slater",
                            Image = "https://imgur.com/2g8nS0W.jpg",
                            Name = "Pea soup with pancetta",
                            Steps = "Heat the chicken stock in a saucepan until it is simmering. Add the peas and simmer for 2 minutes, or until just tender. Stir in the tarragon and salt.##Transfer the mixture to a food processor and blend for a few short blasts to a rough-textured soup. Return the soup to the saucepan and keep warm over a low heat.##Using a pair of tongs, heat each slice of pancetta over the gas flame of your hob for a few seconds until it crisps up. (Alternatively, preheat your grill to its highest setting, lay the slices of pancetta onto a baking tray and grill for 1-2 minutes, or until crisp.)##To serve, ladle the soup into bowls. Break the crisp pancetta into pieces and sprinkle on top of the soup."
                        },
                        new
                        {
                            Id = new Guid("1970b676-b65e-43e4-b50c-1d243024d417"),
                            Author = "Paul Rankin",
                            Image = "https://i.imgur.com/qvrXDy6.jpg",
                            Name = "Noodle salad with chilli nuts",
                            Steps = "For the noodle salad, put the vegetable oil, soy sauce and honey in a large bowl and mix well.##Add the cucumber, pepper and cooked noodles, season with salt and pepper and mix well.##For the chilli nuts, heat the vegetable oil in a frying pan over a medium heat and fry the peanuts for 3-4 minutes. Drain off the oil and fry for a further 2-3 minutes, then add the salt and chilli and stir well to coat the nuts.##Put the noodle salad in a bowl, sprinkle over the nuts and serve."
                        },
                        new
                        {
                            Id = new Guid("f3235d51-8434-48c5-94bf-4a9817c713eb"),
                            Author = "Gino D'Acampo",
                            Image = "https://i.imgur.com/HtxaFZ1.jpg",
                            Name = "Amaretti biscuits",
                            Steps = "Preheat the oven to 170C/325F/Gas 3.##In a large bowl beat the egg whites until firm. Mix the sugar and the almonds gently into it. Add the amaretto liquor and fold in gently until you have a smooth paste.##Place some baking paper on a baking tray and lightly brush with butter. Using a teaspoon place small heaps of the mixture approximately 2cm/¾in apart, as they will expand while cooking. Bake for approximately 15 minutes until golden brown. Leave to cool slightly then serve or store in an air-tight container.##"
                        },
                        new
                        {
                            Id = new Guid("e33858d3-5537-48fc-929b-e11813a2c204"),
                            Author = "Michel Roux Jr.",
                            Image = "https://i.imgur.com/cJSPnE1.jpg",
                            Name = "Madeleines",
                            Steps = "Preheat the oven to 200C/400F/Gas 6. Brush the madeleine tray with melted butter then shake in a little flour to coat, tapping out the excess.##Whisk together the eggs and the sugar in a bowl until frothy. Lightly whisk in the remaining ingredients. Leave to stand for 20 minutes before carefully pouring into the prepared madeleine tray.##Bake for 8-10 minutes, or until the mixture has risen a little in the middle and is fully cooked through. Transfer the madeleines to a wire rack and leave for a few minutes to cool slightly. These are best eaten within an hour of cooking.##"
                        });
                });

            modelBuilder.Entity("DATA.Models.RecipeIngredientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IngredientEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Quantity")
                        .HasColumnType("float(8)");

                    b.Property<Guid>("RecipeEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IngredientEntityId");

                    b.HasIndex("RecipeEntityId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5952ea73-435d-4ad9-9263-27033eae894f"),
                            IngredientEntityId = new Guid("a2e7fe9d-62ce-499d-bad7-374d5f5ea324"),
                            Quantity = 1f,
                            RecipeEntityId = new Guid("e953117d-9c83-4484-a67c-ab23d2e9d7a4"),
                            Unit = "l"
                        },
                        new
                        {
                            Id = new Guid("00cca4bb-d1a7-4083-bdaa-2f85248298bc"),
                            IngredientEntityId = new Guid("39cf9a94-6d89-4749-8b95-e46cf1f7e3f2"),
                            Quantity = 500f,
                            RecipeEntityId = new Guid("e953117d-9c83-4484-a67c-ab23d2e9d7a4"),
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("12f082aa-c0ce-4f4b-aed1-efcd2771ce43"),
                            IngredientEntityId = new Guid("6ec75545-bc1f-4d22-9567-a0332acac633"),
                            Quantity = 10f,
                            RecipeEntityId = new Guid("e953117d-9c83-4484-a67c-ab23d2e9d7a4"),
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("457bc47e-6911-417a-841f-3d3cc5773cba"),
                            IngredientEntityId = new Guid("60c1ee57-6b8d-4c7b-b7c4-c243ac4eb589"),
                            Quantity = 1f,
                            RecipeEntityId = new Guid("e953117d-9c83-4484-a67c-ab23d2e9d7a4"),
                            Unit = "pinch"
                        },
                        new
                        {
                            Id = new Guid("5fabd9b0-2410-428a-9f6e-2af079ad4c13"),
                            IngredientEntityId = new Guid("a8053e3a-81f4-4e9f-a873-4fe43132dabf"),
                            Quantity = 4f,
                            RecipeEntityId = new Guid("e953117d-9c83-4484-a67c-ab23d2e9d7a4"),
                            Unit = "slice"
                        },
                        new
                        {
                            Id = new Guid("af8936d8-ebdd-48e2-9b41-0d45014545ca"),
                            IngredientEntityId = new Guid("9298906d-329f-491f-9c56-acd583a3ac58"),
                            Quantity = 1f,
                            RecipeEntityId = new Guid("1970b676-b65e-43e4-b50c-1d243024d417"),
                            Unit = "tsp"
                        },
                        new
                        {
                            Id = new Guid("2480ccb0-cd33-49f9-9087-4479ee991158"),
                            IngredientEntityId = new Guid("899c7d60-d9b5-4bcd-ad7f-bec831ada320"),
                            Quantity = 1f,
                            RecipeEntityId = new Guid("1970b676-b65e-43e4-b50c-1d243024d417"),
                            Unit = "tsp"
                        },
                        new
                        {
                            Id = new Guid("b9e4dec8-77ff-4ab4-92d5-aad8fbce43b4"),
                            IngredientEntityId = new Guid("e8433ed7-3926-42ca-a6a0-35ad096417c0"),
                            Quantity = 2f,
                            RecipeEntityId = new Guid("1970b676-b65e-43e4-b50c-1d243024d417"),
                            Unit = "tsp"
                        },
                        new
                        {
                            Id = new Guid("56967215-9560-4a2f-8c32-44a222a6bdf0"),
                            IngredientEntityId = new Guid("ab38a6df-ae99-4be9-b13c-c135fdb6edc4"),
                            Quantity = 0.25f,
                            RecipeEntityId = new Guid("1970b676-b65e-43e4-b50c-1d243024d417"),
                            Unit = ""
                        },
                        new
                        {
                            Id = new Guid("78f8dd58-16c8-459e-a483-00b364cc8cb2"),
                            IngredientEntityId = new Guid("c6a33876-00f8-43f7-85f1-bf09cbdb444c"),
                            Quantity = 0.25f,
                            RecipeEntityId = new Guid("1970b676-b65e-43e4-b50c-1d243024d417"),
                            Unit = ""
                        },
                        new
                        {
                            Id = new Guid("bebb10ee-3f89-4af1-afd8-d2f87415e1a8"),
                            IngredientEntityId = new Guid("a255606f-ecbb-42a4-a19a-261667750af0"),
                            Quantity = 0.5f,
                            RecipeEntityId = new Guid("1970b676-b65e-43e4-b50c-1d243024d417"),
                            Unit = "tsp"
                        },
                        new
                        {
                            Id = new Guid("33296163-b994-4afb-9598-219fbd8bc799"),
                            IngredientEntityId = new Guid("a3cbe4b2-22e0-466f-84ab-9e182fd412ad"),
                            Quantity = 100f,
                            RecipeEntityId = new Guid("1970b676-b65e-43e4-b50c-1d243024d417"),
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("8f12ecf5-7988-43d3-91de-5e6a7f098814"),
                            IngredientEntityId = new Guid("b1d5598b-19c6-462d-9245-880e16581ce5"),
                            Quantity = 1f,
                            RecipeEntityId = new Guid("1970b676-b65e-43e4-b50c-1d243024d417"),
                            Unit = "pinch"
                        },
                        new
                        {
                            Id = new Guid("779b500a-3f21-4f7e-877e-dd9132b693bd"),
                            IngredientEntityId = new Guid("9298906d-329f-491f-9c56-acd583a3ac58"),
                            Quantity = 1f,
                            RecipeEntityId = new Guid("1970b676-b65e-43e4-b50c-1d243024d417"),
                            Unit = "tsp"
                        },
                        new
                        {
                            Id = new Guid("5bd25d0a-73e2-48f0-9962-69b25d43adcd"),
                            IngredientEntityId = new Guid("4b702393-2272-4e1c-8227-78dab874decf"),
                            Quantity = 50f,
                            RecipeEntityId = new Guid("1970b676-b65e-43e4-b50c-1d243024d417"),
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("d73fb2b7-c531-4ef4-9ca5-449f052e8f11"),
                            IngredientEntityId = new Guid("c54d0495-4fea-4746-a3a0-b6d0655e26e9"),
                            Quantity = 0.5f,
                            RecipeEntityId = new Guid("1970b676-b65e-43e4-b50c-1d243024d417"),
                            Unit = "tsp"
                        },
                        new
                        {
                            Id = new Guid("93444c1a-62a4-4130-94cf-7887182721fc"),
                            IngredientEntityId = new Guid("49c14bf5-f6d5-4dec-88b3-eb1b41da15a1"),
                            Quantity = 4f,
                            RecipeEntityId = new Guid("f3235d51-8434-48c5-94bf-4a9817c713eb"),
                            Unit = ""
                        },
                        new
                        {
                            Id = new Guid("cad2e95a-9c6d-484c-8113-15806b4fc68b"),
                            IngredientEntityId = new Guid("318eed32-374a-440e-960a-b3b8d366975b"),
                            Quantity = 340f,
                            RecipeEntityId = new Guid("f3235d51-8434-48c5-94bf-4a9817c713eb"),
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("855cb133-297f-4846-a1af-63f7e0c67328"),
                            IngredientEntityId = new Guid("42cb1156-0538-469d-9ff5-f2ff86f02b59"),
                            Quantity = 340f,
                            RecipeEntityId = new Guid("f3235d51-8434-48c5-94bf-4a9817c713eb"),
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("cdb1356e-3241-450d-86ba-a33f5a2b3502"),
                            IngredientEntityId = new Guid("4afffe88-426f-4556-ba73-cbff3022d052"),
                            Quantity = 30f,
                            RecipeEntityId = new Guid("f3235d51-8434-48c5-94bf-4a9817c713eb"),
                            Unit = "ml"
                        },
                        new
                        {
                            Id = new Guid("f26b2c5e-0e9a-4c0a-8314-1322ade1f9c6"),
                            IngredientEntityId = new Guid("21622f46-38a6-48b8-ae4e-4db58f4ca206"),
                            Quantity = 1f,
                            RecipeEntityId = new Guid("f3235d51-8434-48c5-94bf-4a9817c713eb"),
                            Unit = "slice"
                        },
                        new
                        {
                            Id = new Guid("c22b262b-ca21-416f-9403-23c31fcbaacb"),
                            IngredientEntityId = new Guid("ef8a6b6c-b4b9-4731-9e97-b6070478ec78"),
                            Quantity = 2f,
                            RecipeEntityId = new Guid("e33858d3-5537-48fc-929b-e11813a2c204"),
                            Unit = ""
                        },
                        new
                        {
                            Id = new Guid("e159cbf9-9dee-460a-9374-49ce9b279b47"),
                            IngredientEntityId = new Guid("726e428a-5f9d-4cd9-87a2-b3c8e007fce8"),
                            Quantity = 100f,
                            RecipeEntityId = new Guid("e33858d3-5537-48fc-929b-e11813a2c204"),
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("65e29cb1-f183-4ac7-ad4a-37b1ecf40e69"),
                            IngredientEntityId = new Guid("6fa9c5bf-57ca-4092-a38f-808d569ed079"),
                            Quantity = 100f,
                            RecipeEntityId = new Guid("e33858d3-5537-48fc-929b-e11813a2c204"),
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("9a12e6d8-1068-402d-a67f-e9b29d3ee190"),
                            IngredientEntityId = new Guid("7175a1df-a56f-4f1e-97b5-4bcb3590f46a"),
                            Quantity = 1f,
                            RecipeEntityId = new Guid("e33858d3-5537-48fc-929b-e11813a2c204"),
                            Unit = ""
                        },
                        new
                        {
                            Id = new Guid("871c7a38-77bc-48ae-a505-fddceafbe1ae"),
                            IngredientEntityId = new Guid("73d32e88-4808-4d46-aa39-5356e5abd1e4"),
                            Quantity = 0.75f,
                            RecipeEntityId = new Guid("e33858d3-5537-48fc-929b-e11813a2c204"),
                            Unit = "tsp"
                        },
                        new
                        {
                            Id = new Guid("80fd04da-b237-4c9e-892d-7526c8f73dbb"),
                            IngredientEntityId = new Guid("4eba77e8-1217-4917-99b6-ce5825b04cc3"),
                            Quantity = 100f,
                            RecipeEntityId = new Guid("e33858d3-5537-48fc-929b-e11813a2c204"),
                            Unit = "g"
                        });
                });

            modelBuilder.Entity("DATA.Models.RecipeIngredientEntity", b =>
                {
                    b.HasOne("DATA.Models.IngredientEntity", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATA.Models.RecipeEntity", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("DATA.Models.IngredientEntity", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("DATA.Models.RecipeEntity", b =>
                {
                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
