// <auto-generated />
using System;
using DATA.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DATA.Migrations
{
    [DbContext(typeof(RecipeContext))]
    [Migration("20210915100431_AddData")]
    partial class AddData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DATA.Models.IngredientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0f3cbc7-333f-4489-9bf8-b226d7cf1005"),
                            Name = "chicken stock"
                        },
                        new
                        {
                            Id = new Guid("e4701b80-6760-479d-b386-05bbd4973083"),
                            Name = "frozen peas"
                        },
                        new
                        {
                            Id = new Guid("a3f6a116-5876-46fd-bc4e-ba5e237c38d5"),
                            Name = "tarragon leaves"
                        },
                        new
                        {
                            Id = new Guid("3575e455-2b14-42a6-849d-63c842fb45f0"),
                            Name = "salt"
                        },
                        new
                        {
                            Id = new Guid("16709348-54bf-4604-8bfe-e91613098619"),
                            Name = "pancetta"
                        },
                        new
                        {
                            Id = new Guid("fbf38fd3-20e5-4ff2-848c-95589817edb1"),
                            Name = "vegetable oil"
                        },
                        new
                        {
                            Id = new Guid("c604855e-5b59-470a-8656-a7e61d2652f5"),
                            Name = "soy sauce"
                        },
                        new
                        {
                            Id = new Guid("85d44332-543b-4633-aed7-89d05595b81b"),
                            Name = "honey"
                        },
                        new
                        {
                            Id = new Guid("b14bd30e-d39f-4527-aa0c-58851aff5c35"),
                            Name = "cucumber"
                        },
                        new
                        {
                            Id = new Guid("dfca111d-d72f-47c5-b2a4-261d55dbbee8"),
                            Name = "pepper"
                        },
                        new
                        {
                            Id = new Guid("a82677c5-7ce0-41f8-845e-b5c0183580ed"),
                            Name = "salt"
                        },
                        new
                        {
                            Id = new Guid("6a826480-a63f-40d5-a8d4-ccac1c18a8d4"),
                            Name = "egg noodles"
                        },
                        new
                        {
                            Id = new Guid("d7e6526f-64dc-4dc5-b96d-48c176e0dd46"),
                            Name = "black pepper"
                        },
                        new
                        {
                            Id = new Guid("3c183ece-3b2f-4af5-a2ce-6a8a42db3f1f"),
                            Name = "peanuts"
                        },
                        new
                        {
                            Id = new Guid("a6f39663-b582-4648-a585-8f4ffe9a79b7"),
                            Name = "chilli flakes"
                        },
                        new
                        {
                            Id = new Guid("28335a47-c52e-4ff1-bc8f-4f7b922c7759"),
                            Name = "egg white"
                        },
                        new
                        {
                            Id = new Guid("037d069a-d1af-4da2-a051-459e603ba6c3"),
                            Name = "caster sugar"
                        },
                        new
                        {
                            Id = new Guid("1af0c3b3-7a2e-4d16-a9b4-4041c746f85c"),
                            Name = "ground almonds"
                        },
                        new
                        {
                            Id = new Guid("9a9f5cf7-67da-48d0-85ba-bfc2779d4aa1"),
                            Name = "amaretto liqueur"
                        },
                        new
                        {
                            Id = new Guid("6e222e6e-42fe-42cc-a9f3-4a541d1beb49"),
                            Name = "butter"
                        },
                        new
                        {
                            Id = new Guid("a16a0bae-488f-40db-a37a-4facd8a68b7d"),
                            Name = "egg"
                        },
                        new
                        {
                            Id = new Guid("39254afd-9dec-422b-9db3-dda37ace2b04"),
                            Name = "caster sugar"
                        },
                        new
                        {
                            Id = new Guid("b5484488-3429-4d1b-aac4-2b6d5c428935"),
                            Name = "plain flour"
                        },
                        new
                        {
                            Id = new Guid("32cb6f16-bdc3-458a-9671-d82258dbc64e"),
                            Name = "lemon"
                        },
                        new
                        {
                            Id = new Guid("180fd132-aa23-4a40-90d7-9a2b386a2dd9"),
                            Name = "baking powder"
                        },
                        new
                        {
                            Id = new Guid("435af9f0-2612-41a3-badf-79fa0ef9160d"),
                            Name = "butter"
                        });
                });

            modelBuilder.Entity("DATA.Models.RecipeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CreatedOn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Steps")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ec7fe29b-bd54-4096-9b32-6b53e42b957b"),
                            Author = "Nigel Slater",
                            Image = "https://imgur.com/2g8nS0W.jpg",
                            Name = "Pea soup with pancetta",
                            Steps = "Heat the chicken stock in a saucepan until it is simmering. Add the peas and simmer for 2 minutes, or until just tender. Stir in the tarragon and salt.##Transfer the mixture to a food processor and blend for a few short blasts to a rough-textured soup. Return the soup to the saucepan and keep warm over a low heat.##Using a pair of tongs, heat each slice of pancetta over the gas flame of your hob for a few seconds until it crisps up. (Alternatively, preheat your grill to its highest setting, lay the slices of pancetta onto a baking tray and grill for 1-2 minutes, or until crisp).##To serve, ladle the soup into bowls. Break the crisp pancetta into pieces and sprinkle on top of the soup."
                        },
                        new
                        {
                            Id = new Guid("7cf66a77-d86b-4d75-b732-b038f729df51"),
                            Author = "Paul Rankin",
                            Image = "https://i.imgur.com/qvrXDy6.jpg",
                            Name = "Noodle salad with chilli nuts",
                            Steps = "For the noodle salad, put the vegetable oil, soy sauce and honey in a large bowl and mix well.##Add the cucumber, pepper and cooked noodles, season with salt and pepper and mix well.##For the chilli nuts, heat the vegetable oil in a frying pan over a medium heat and fry the peanuts for 3-4 minutes. Drain off the oil and fry for a further 2-3 minutes, then add the salt and chilli and stir well to coat the nuts.##Put the noodle salad in a bowl, sprinkle over the nuts and serve."
                        },
                        new
                        {
                            Id = new Guid("5d9a728f-736d-440b-919e-ed976591284b"),
                            Author = "Gino D'Acampo",
                            Image = "https://i.imgur.com/HtxaFZ1.jpg",
                            Name = "Amaretti biscuits",
                            Steps = "Preheat the oven to 170C/325F/Gas 3.##In a large bowl beat the egg whites until firm. Mix the sugar and the almonds gently into it. Add the amaretto liquor and fold in gently until you have a smooth paste.##Place some baking paper on a baking tray and lightly brush with butter. Using a teaspoon place small heaps of the mixture approximately 2cm/¾in apart, as they will expand while cooking. Bake for approximately 15 minutes until golden brown. Leave to cool slightly then serve or store in an air-tight container."
                        },
                        new
                        {
                            Id = new Guid("3c9a34b1-5447-4d71-b1c9-be98698524aa"),
                            Author = "Michel Roux Jr.",
                            Image = "https://i.imgur.com/cJSPnE1.jpg",
                            Name = "Madeleines",
                            Steps = "Preheat the oven to 200C/400F/Gas 6. Brush the madeleine tray with melted butter then shake in a little flour to coat, tapping out the excess.##Whisk together the eggs and the sugar in a bowl until frothy. Lightly whisk in the remaining ingredients. Leave to stand for 20 minutes before carefully pouring into the prepared madeleine tray.##Bake for 8-10 minutes, or until the mixture has risen a little in the middle and is fully cooked through. Transfer the madeleines to a wire rack and leave for a few minutes to cool slightly. These are best eaten within an hour of cooking."
                        });
                });

            modelBuilder.Entity("DATA.Models.RecipeIngredientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IngredientEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Quantity")
                        .HasColumnType("float(8)");

                    b.Property<Guid>("RecipeEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UnitEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IngredientEntityId");

                    b.HasIndex("RecipeEntityId");

                    b.HasIndex("UnitEntityId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ef2023cf-64e1-4fdf-8ac6-38a4f30916b8"),
                            IngredientEntityId = new Guid("d0f3cbc7-333f-4489-9bf8-b226d7cf1005"),
                            Quantity = 1f,
                            RecipeEntityId = new Guid("ec7fe29b-bd54-4096-9b32-6b53e42b957b"),
                            UnitEntityId = new Guid("ac78adf3-31ef-4028-9971-12f535a38229")
                        },
                        new
                        {
                            Id = new Guid("889c07f5-e4f7-4ca2-b450-3bae3c2b3452"),
                            IngredientEntityId = new Guid("e4701b80-6760-479d-b386-05bbd4973083"),
                            Quantity = 500f,
                            RecipeEntityId = new Guid("ec7fe29b-bd54-4096-9b32-6b53e42b957b"),
                            UnitEntityId = new Guid("64db8390-9471-4776-94e1-7dd077e3f072")
                        },
                        new
                        {
                            Id = new Guid("7a671ab0-1e06-4610-bcf7-dd8ad34806e5"),
                            IngredientEntityId = new Guid("a3f6a116-5876-46fd-bc4e-ba5e237c38d5"),
                            Quantity = 10f,
                            RecipeEntityId = new Guid("ec7fe29b-bd54-4096-9b32-6b53e42b957b"),
                            UnitEntityId = new Guid("64db8390-9471-4776-94e1-7dd077e3f072")
                        },
                        new
                        {
                            Id = new Guid("5bd626c3-4323-4c53-8fd5-b24508dad60a"),
                            IngredientEntityId = new Guid("3575e455-2b14-42a6-849d-63c842fb45f0"),
                            Quantity = 1f,
                            RecipeEntityId = new Guid("ec7fe29b-bd54-4096-9b32-6b53e42b957b"),
                            UnitEntityId = new Guid("45a0c62c-a6a1-47d8-bc2d-94983253fd48")
                        },
                        new
                        {
                            Id = new Guid("bad2ab30-c3a9-4794-83c6-0fe2aa488817"),
                            IngredientEntityId = new Guid("16709348-54bf-4604-8bfe-e91613098619"),
                            Quantity = 4f,
                            RecipeEntityId = new Guid("ec7fe29b-bd54-4096-9b32-6b53e42b957b"),
                            UnitEntityId = new Guid("0511352c-a306-4b40-88ab-6abdb0bdccca")
                        },
                        new
                        {
                            Id = new Guid("2ed896e3-83fa-4496-b7f6-26c8dc79bfcd"),
                            IngredientEntityId = new Guid("fbf38fd3-20e5-4ff2-848c-95589817edb1"),
                            Quantity = 1f,
                            RecipeEntityId = new Guid("7cf66a77-d86b-4d75-b732-b038f729df51"),
                            UnitEntityId = new Guid("e45732a6-b3c0-4ef3-a405-f7c989f50f1e")
                        },
                        new
                        {
                            Id = new Guid("b79df886-533d-4171-90a4-26a9568b102c"),
                            IngredientEntityId = new Guid("c604855e-5b59-470a-8656-a7e61d2652f5"),
                            Quantity = 1f,
                            RecipeEntityId = new Guid("7cf66a77-d86b-4d75-b732-b038f729df51"),
                            UnitEntityId = new Guid("e45732a6-b3c0-4ef3-a405-f7c989f50f1e")
                        },
                        new
                        {
                            Id = new Guid("3c4f5d0b-e34e-4bef-839b-febb235905a3"),
                            IngredientEntityId = new Guid("85d44332-543b-4633-aed7-89d05595b81b"),
                            Quantity = 2f,
                            RecipeEntityId = new Guid("7cf66a77-d86b-4d75-b732-b038f729df51"),
                            UnitEntityId = new Guid("e45732a6-b3c0-4ef3-a405-f7c989f50f1e")
                        },
                        new
                        {
                            Id = new Guid("88acac1b-3a57-43f3-aabd-4334ddb02374"),
                            IngredientEntityId = new Guid("b14bd30e-d39f-4527-aa0c-58851aff5c35"),
                            Quantity = 0.25f,
                            RecipeEntityId = new Guid("7cf66a77-d86b-4d75-b732-b038f729df51"),
                            UnitEntityId = new Guid("5169563e-d16d-481b-933f-ab97a6c4fbef")
                        },
                        new
                        {
                            Id = new Guid("36525bd3-3c27-4fc7-831f-354fa6d6a235"),
                            IngredientEntityId = new Guid("dfca111d-d72f-47c5-b2a4-261d55dbbee8"),
                            Quantity = 0.25f,
                            RecipeEntityId = new Guid("7cf66a77-d86b-4d75-b732-b038f729df51"),
                            UnitEntityId = new Guid("5169563e-d16d-481b-933f-ab97a6c4fbef")
                        },
                        new
                        {
                            Id = new Guid("98b853cc-3db4-4022-82af-b992c2df5b51"),
                            IngredientEntityId = new Guid("a82677c5-7ce0-41f8-845e-b5c0183580ed"),
                            Quantity = 0.5f,
                            RecipeEntityId = new Guid("7cf66a77-d86b-4d75-b732-b038f729df51"),
                            UnitEntityId = new Guid("e45732a6-b3c0-4ef3-a405-f7c989f50f1e")
                        },
                        new
                        {
                            Id = new Guid("7f32f67f-5620-4a98-b322-9baf60c8cb85"),
                            IngredientEntityId = new Guid("6a826480-a63f-40d5-a8d4-ccac1c18a8d4"),
                            Quantity = 100f,
                            RecipeEntityId = new Guid("7cf66a77-d86b-4d75-b732-b038f729df51"),
                            UnitEntityId = new Guid("64db8390-9471-4776-94e1-7dd077e3f072")
                        },
                        new
                        {
                            Id = new Guid("af803fd3-3569-4b2f-8914-45f67cd258e3"),
                            IngredientEntityId = new Guid("d7e6526f-64dc-4dc5-b96d-48c176e0dd46"),
                            Quantity = 1f,
                            RecipeEntityId = new Guid("7cf66a77-d86b-4d75-b732-b038f729df51"),
                            UnitEntityId = new Guid("45a0c62c-a6a1-47d8-bc2d-94983253fd48")
                        },
                        new
                        {
                            Id = new Guid("1e240b06-3f19-47aa-94a0-4aa622b26208"),
                            IngredientEntityId = new Guid("fbf38fd3-20e5-4ff2-848c-95589817edb1"),
                            Quantity = 1f,
                            RecipeEntityId = new Guid("7cf66a77-d86b-4d75-b732-b038f729df51"),
                            UnitEntityId = new Guid("e45732a6-b3c0-4ef3-a405-f7c989f50f1e")
                        },
                        new
                        {
                            Id = new Guid("a1dc6873-bbd2-4f07-b92d-9f43a06f159c"),
                            IngredientEntityId = new Guid("3c183ece-3b2f-4af5-a2ce-6a8a42db3f1f"),
                            Quantity = 50f,
                            RecipeEntityId = new Guid("7cf66a77-d86b-4d75-b732-b038f729df51"),
                            UnitEntityId = new Guid("64db8390-9471-4776-94e1-7dd077e3f072")
                        },
                        new
                        {
                            Id = new Guid("51743372-d8dc-4772-9129-45c46c4c8156"),
                            IngredientEntityId = new Guid("a6f39663-b582-4648-a585-8f4ffe9a79b7"),
                            Quantity = 0.5f,
                            RecipeEntityId = new Guid("7cf66a77-d86b-4d75-b732-b038f729df51"),
                            UnitEntityId = new Guid("e45732a6-b3c0-4ef3-a405-f7c989f50f1e")
                        },
                        new
                        {
                            Id = new Guid("649aef2f-1f8f-4905-8b0c-8116268b6734"),
                            IngredientEntityId = new Guid("28335a47-c52e-4ff1-bc8f-4f7b922c7759"),
                            Quantity = 4f,
                            RecipeEntityId = new Guid("5d9a728f-736d-440b-919e-ed976591284b"),
                            UnitEntityId = new Guid("5169563e-d16d-481b-933f-ab97a6c4fbef")
                        },
                        new
                        {
                            Id = new Guid("fdf245e7-a096-4290-8382-fec05df2c82b"),
                            IngredientEntityId = new Guid("037d069a-d1af-4da2-a051-459e603ba6c3"),
                            Quantity = 340f,
                            RecipeEntityId = new Guid("5d9a728f-736d-440b-919e-ed976591284b"),
                            UnitEntityId = new Guid("64db8390-9471-4776-94e1-7dd077e3f072")
                        },
                        new
                        {
                            Id = new Guid("1121327a-099d-4fb7-add9-17ded7b9b04b"),
                            IngredientEntityId = new Guid("1af0c3b3-7a2e-4d16-a9b4-4041c746f85c"),
                            Quantity = 340f,
                            RecipeEntityId = new Guid("5d9a728f-736d-440b-919e-ed976591284b"),
                            UnitEntityId = new Guid("64db8390-9471-4776-94e1-7dd077e3f072")
                        },
                        new
                        {
                            Id = new Guid("66b25345-3963-4d76-b7ac-d637f58013cc"),
                            IngredientEntityId = new Guid("9a9f5cf7-67da-48d0-85ba-bfc2779d4aa1"),
                            Quantity = 30f,
                            RecipeEntityId = new Guid("5d9a728f-736d-440b-919e-ed976591284b"),
                            UnitEntityId = new Guid("678fc5ec-a4aa-47dd-ad69-e7fd4fd8a9b0")
                        },
                        new
                        {
                            Id = new Guid("dde02711-151a-491c-818c-4c5080d4e05e"),
                            IngredientEntityId = new Guid("6e222e6e-42fe-42cc-a9f3-4a541d1beb49"),
                            Quantity = 1f,
                            RecipeEntityId = new Guid("5d9a728f-736d-440b-919e-ed976591284b"),
                            UnitEntityId = new Guid("0511352c-a306-4b40-88ab-6abdb0bdccca")
                        },
                        new
                        {
                            Id = new Guid("66e79c14-0151-4513-a6fa-a3bc1c313256"),
                            IngredientEntityId = new Guid("a16a0bae-488f-40db-a37a-4facd8a68b7d"),
                            Quantity = 2f,
                            RecipeEntityId = new Guid("3c9a34b1-5447-4d71-b1c9-be98698524aa"),
                            UnitEntityId = new Guid("5169563e-d16d-481b-933f-ab97a6c4fbef")
                        },
                        new
                        {
                            Id = new Guid("e23bcf38-ec30-40ed-8dc1-4893d6a7f87e"),
                            IngredientEntityId = new Guid("39254afd-9dec-422b-9db3-dda37ace2b04"),
                            Quantity = 100f,
                            RecipeEntityId = new Guid("3c9a34b1-5447-4d71-b1c9-be98698524aa"),
                            UnitEntityId = new Guid("64db8390-9471-4776-94e1-7dd077e3f072")
                        },
                        new
                        {
                            Id = new Guid("755f2652-e89b-485e-868f-c0cd87387c1e"),
                            IngredientEntityId = new Guid("b5484488-3429-4d1b-aac4-2b6d5c428935"),
                            Quantity = 100f,
                            RecipeEntityId = new Guid("3c9a34b1-5447-4d71-b1c9-be98698524aa"),
                            UnitEntityId = new Guid("64db8390-9471-4776-94e1-7dd077e3f072")
                        },
                        new
                        {
                            Id = new Guid("520a0f92-8e57-4213-8883-c06d4cba1775"),
                            IngredientEntityId = new Guid("32cb6f16-bdc3-458a-9671-d82258dbc64e"),
                            Quantity = 1f,
                            RecipeEntityId = new Guid("3c9a34b1-5447-4d71-b1c9-be98698524aa"),
                            UnitEntityId = new Guid("5169563e-d16d-481b-933f-ab97a6c4fbef")
                        },
                        new
                        {
                            Id = new Guid("031355d1-508a-48dc-a79a-a8803fb0e667"),
                            IngredientEntityId = new Guid("180fd132-aa23-4a40-90d7-9a2b386a2dd9"),
                            Quantity = 0.75f,
                            RecipeEntityId = new Guid("3c9a34b1-5447-4d71-b1c9-be98698524aa"),
                            UnitEntityId = new Guid("e45732a6-b3c0-4ef3-a405-f7c989f50f1e")
                        },
                        new
                        {
                            Id = new Guid("878c2274-2721-42df-a75a-f527761a1540"),
                            IngredientEntityId = new Guid("435af9f0-2612-41a3-badf-79fa0ef9160d"),
                            Quantity = 100f,
                            RecipeEntityId = new Guid("3c9a34b1-5447-4d71-b1c9-be98698524aa"),
                            UnitEntityId = new Guid("64db8390-9471-4776-94e1-7dd077e3f072")
                        });
                });

            modelBuilder.Entity("DATA.Models.UnitEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ac78adf3-31ef-4028-9971-12f535a38229"),
                            Name = "l"
                        },
                        new
                        {
                            Id = new Guid("64db8390-9471-4776-94e1-7dd077e3f072"),
                            Name = "g"
                        },
                        new
                        {
                            Id = new Guid("45a0c62c-a6a1-47d8-bc2d-94983253fd48"),
                            Name = "pinch"
                        },
                        new
                        {
                            Id = new Guid("0511352c-a306-4b40-88ab-6abdb0bdccca"),
                            Name = "slice"
                        },
                        new
                        {
                            Id = new Guid("e45732a6-b3c0-4ef3-a405-f7c989f50f1e"),
                            Name = "tsp"
                        },
                        new
                        {
                            Id = new Guid("678fc5ec-a4aa-47dd-ad69-e7fd4fd8a9b0"),
                            Name = "ml"
                        },
                        new
                        {
                            Id = new Guid("5169563e-d16d-481b-933f-ab97a6c4fbef"),
                            Name = ""
                        });
                });

            modelBuilder.Entity("DATA.Models.RecipeIngredientEntity", b =>
                {
                    b.HasOne("DATA.Models.IngredientEntity", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATA.Models.RecipeEntity", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATA.Models.UnitEntity", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("DATA.Models.IngredientEntity", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("DATA.Models.RecipeEntity", b =>
                {
                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
